### ISSUE TITLE
Update Ollama to at least 0.2.1

### ISSUE THREAD

**Issue by fbricon** [rh-aiservices-bu/llm-on-openshift#73]
I'd like to leverage the new added v1/models endpoint that was [added](https://github.com/ollama/ollama/pull/5007) last week. Could you please rebuild/publish a new image on Quay.io based on Ollama [0.2.1](https://github.com/ollama/ollama/releases/tag/v0.2.1). 

https://github.com/rh-aiservices-bu/llm-on-openshift/blob/1b864db3eb23a4fdaa7f2c57ab58ad2a25711a94/llm-servers/ollama/Containerfile#L2

**Comment by guimou** [comment]
Fixed in #79 , although I went straight to 0.2.8
