### ISSUE TITLE
Langchain-Milvus-Ingest.ipynb and Langchain-Milvus-Query-nomic.ipynb crashing

### ISSUE THREAD

**Issue by cfchase** [rh-aiservices-bu/llm-on-openshift#93]
<img width="502" alt="Screenshot 2024-10-16 at 3 19 13 PM" src="https://github.com/user-attachments/assets/c6ea39b9-5470-48f1-acc3-f6f9feeeff63">

**Comment by guimou** [comment]
Fixed by #92
